### PR TITLE
Add Cloud Platforms support request template

### PR DESCRIPTION
**Pull request by lukaszraczylo**

### CODE REVIEW

**Comment by tatyree** [comment]
https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by kcbotsh** [comment]
child of parent ticket 

https://waffle.io/ministryofjustice/cloud-platform/cards/5afae334f19c77001c633d80

**Comment by lukaszraczylo** [comment]
This work connects to #41

**Comment by kcbotsh** [comment]
Tested this and happy the process works as intended

**Pull request merged**
