### PR TITLE
Add Todd's approval

### PR DESCRIPTION
**Pull request by kalbir**
Adding Todd's name to the support doc to show he agrees with the support
processes outlined here.

### CODE REVIEW

**Comment by tatyree** [comment]
I'm happy to agree, but this is only the list of signatories.   Can point me at the link of the documentation I'm endorsing, please? :)

**Comment by kalbir** [comment]
@tatyree it's that same document, you can expand the diff to see the whole thing.

**Comment by tatyree** [comment]
Under working hours, first para, last sentence: "person on call **has is** coming in to the office".

**Comment by tatyree** [comment]
Add a paragraph to 'User support tickets' stating: "New support tickets added by users who are not part of the WebOps Github team will not automatically appear in the `Support To Do` column yet.  This is due to Github permissions not being fine-grained enough to permit MoJ organisation users who are not on WebOps to create the necessary label. This should be fixed soon.  Until it is you may see some support tickets appear in `Inbox` and not `Support To Do`.

**Comment by tatyree** [comment]
"Our incident process", ordered list item 2: 
"impacted" not "impacting".   
I'd also change "regular schedules" to "regular intervals". 
"The people that they communicate to include" - maybe "People to include in these communications:"

**Comment by kalbir** [comment]
@tatyree I've made those changes

**Pull request merged**
