### PR TITLE
Runbook about Cloud Platform Helm Chart repository

### PR DESCRIPTION
**Pull request by mogaal**
Added a runbook about how to manage the cloud platform repository using github pages.

### CODE REVIEW

**Comment by mogaal** [comment]
Hmmm not sure if I got your idea. At the moment: 

- `master`: the source code of helm charts
- `gh-pages`: the artefacts/tarballs and `index.yaml`. Basically the repository itself.

Is your question related about if we can set the repository itself to the `master` branch instead of `gh-pages`?

**Comment by digitalronin** [comment]
Yes, exactly. Is there any reason not to put the tarballs and yaml files in the master branch, and use that same master branch as the basis of the github pages site?

Also, please could you add the webops team as admins of the repo?

**Comment by mogaal** [comment]
Ohh I followed the [official doc regarding this](https://helm.sh/docs/topics/chart_repository/#github-pages-example) and this is the way selected. 

But I think what you said might be possible, I'll give it a try this afternoon and let you know :)

**Comment by digitalronin** [comment]
If it turns out to be easier to use `gh-pages` for some reason, that's fine.

I'm just hoping we can avoid having a special repo, where we don't do what we do in all the other repos (i.e. we only really care about `master`)

**Comment by digitalronin** [comment]
@mogaal Can this be merged now?

**Pull request merged**
